/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ShowroomsRouteImport } from './routes/showrooms'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as PlannerRoomsIdRouteImport } from './routes/planner.rooms.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomsRoute = ShowroomsRouteImport.update({
  id: '/showrooms',
  path: '/showrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionRoute,
} as any)
const PlannerRoomsIdRoute = PlannerRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => PlannerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRouteWithChildren
  '/quote': typeof QuoteRoute
  '/rooms': typeof RoomsRoute
  '/showrooms': typeof ShowroomsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/planner/rooms/$id': typeof PlannerRoomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRouteWithChildren
  '/quote': typeof QuoteRoute
  '/rooms': typeof RoomsRoute
  '/showrooms': typeof ShowroomsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/planner/rooms/$id': typeof PlannerRoomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRouteWithChildren
  '/quote': typeof QuoteRoute
  '/rooms': typeof RoomsRoute
  '/showrooms': typeof ShowroomsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/planner/rooms/$id': typeof PlannerRoomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/materials'
    | '/planner'
    | '/quote'
    | '/rooms'
    | '/showrooms'
    | '/collection/$slug'
    | '/planner/rooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/materials'
    | '/planner'
    | '/quote'
    | '/rooms'
    | '/showrooms'
    | '/collection/$slug'
    | '/planner/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/materials'
    | '/planner'
    | '/quote'
    | '/rooms'
    | '/showrooms'
    | '/collection/$slug'
    | '/planner/rooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  MaterialsRoute: typeof MaterialsRoute
  PlannerRoute: typeof PlannerRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  RoomsRoute: typeof RoomsRoute
  ShowroomsRoute: typeof ShowroomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showrooms': {
      id: '/showrooms'
      path: '/showrooms'
      fullPath: '/showrooms'
      preLoaderRoute: typeof ShowroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/planner/rooms/$id': {
      id: '/planner/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/planner/rooms/$id'
      preLoaderRoute: typeof PlannerRoomsIdRouteImport
      parentRoute: typeof PlannerRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionSlugRoute: typeof CollectionSlugRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionSlugRoute: CollectionSlugRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

interface PlannerRouteChildren {
  PlannerRoomsIdRoute: typeof PlannerRoomsIdRoute
}

const PlannerRouteChildren: PlannerRouteChildren = {
  PlannerRoomsIdRoute: PlannerRoomsIdRoute,
}

const PlannerRouteWithChildren =
  PlannerRoute._addFileChildren(PlannerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRouteWithChildren,
  MaterialsRoute: MaterialsRoute,
  PlannerRoute: PlannerRouteWithChildren,
  QuoteRoute: QuoteRoute,
  RoomsRoute: RoomsRoute,
  ShowroomsRoute: ShowroomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
